### PR TITLE
First attempt at something resembling a swingable items system to test the viability of the concept

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Makes some items swingable.

This image shows what happens when a mob (green arrow, facing the direction of the arrow) swings with different swingable objects. Numbers show the damage modifier for each tile.
image
First (from left to right, then top to bottom) is stabbing, second is swinging, third is thrusting, and fourth is flailing.

## Why It's Good For The Game
Might make combat slightly more fun? I have no idea

## Changelog
:cl:
add: "swing" based combat
/:cl:

### CODE REVIEW

**Comment by Superyodeler** [comment]
I think it would be best to remove most of the damage modifiers and instead modify the weapon's force. Thrusting is fine, but I'm not sure they're needed on swing and flail.

**Comment by dinnerwoerror** [comment]
now that we have use intent, do we get weapon intent now, and then we will get combat intent like in is12

3920_screenshots_20170309235727_1

**Comment by MarkSuckerberg** [comment]
> 
> 
> I think it would be best to remove most of the damage modifiers and instead modify the weapon's force. Thrusting is fine, but I'm not sure they're needed on swing and flail.

Do you mean modify the force between each hit, or just flatout make it do less damage on certain moves?

**Comment by Vorak2** [comment]
image
Going to sugest that there should be diferent damage modifiers depending on where in the swing it is. like this

**Comment by MarkSuckerberg** [comment]
I can make it slightly more complex, but it's not terribly easy to modify each hit tile precisely.

**Comment by Superyodeler** [comment]
> 
> 
> > I think it would be best to remove most of the damage modifiers and instead modify the weapon's force. Thrusting is fine, but I'm not sure they're needed on swing and flail.
> 
> Do you mean modify the force between each hit, or just flatout make it do less damage on certain moves?

If some items are going to have multiple attack types, this is fine. I thought each item was going to have just one attack.

**Comment by Superyodeler** [comment]
Also #690 funny number

**Comment by Superyodeler** [comment]
Is this ready for review, or is it still WIP?

**Comment by zamolxius** [comment]
https://github.com/tgstation/tgstation/pull/11786 this ancient PR might help you

**Comment by Superyodeler** [comment]
Is this ready for me to take a look at it?

**Pull request closed without merging**
