### PR TITLE
Draft: TGUI Preferences Panel

### PR DESCRIPTION
**Pull request by Maldaris**
## About The Pull Request

Updates the Preferences panel to use TGUI

## Why It's Good For The Game

Lowers the barrier of effort for making changes to character setup/game preferences significantly. It wasn't difficult before, but it does take a lot of effort (and sanity) to work with the `preferences.dm` file's massive amounts of inlined HTML.

## TODO

- [ ] TGUI Backend refactor of Preferences
- [ ] TGUI Views for Preferences Panel
  - [x] Character Setup
  - [ ] Character Appearance
  - [ ] Gear Preferences
  - [ ] OOC Preferences
  - [ ] Game Preferences
  - [ ] Custom Keybindings

## Changelog
:cl:
refactor: rebuilt Preferences Panel using TGUI
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
hot damn

**Comment by Jack7D1** [comment]
I love you

**Comment by Shadowtail117** [comment]
Can you post a screenshot of what it looks like in-game?

**Comment by Maldaris** [comment]
> Can you post a screenshot of what it looks like in-game?

This is heavily WIP at the moment.

**Pull request closed without merging**
