### PR TITLE
Adds the unfollow verb to the mentor tab.

### PR DESCRIPTION
**Pull request by Jack7D1**
## About The Pull Request
Makes it so the Stop-Following verb appears in the mentors tab, adds a check if you're not following anyone.

## Why It's Good For The Game
Basically an ided PR but I was trapped following someone until I was able to figure out that I could type it in the verb bar.

## Changelog
:cl:
fix: Added Stop-Following to the mentors tab
/:cl:

### CODE REVIEW

**Review by Superyodeler — APPROVED** [review]

**Comment by White-Sans** [comment]
#### Test Merge Deployed

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: c8ba3dc7cdadc56616669e4f50905d1aa1b9456a
Server: abfa3735de453c4b57d660b6395b8dd093357c00

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: e8c6725e5975e248cc015d29b3bf53b02312ce87
Pull Request: c8ba3dc7cdadc56616669e4f50905d1aa1b9456a
Server: 8aaf1d92960aed79a6613351246470472346413c

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: c8ba3dc7cdadc56616669e4f50905d1aa1b9456a
Server: e29ee0a0e1b68cab4f437b8af05286a0b7209311

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 0aa285656ec5a9e4960407656abc755fa146f020
Server: 0c46f0c046c353b003e0df0f8b5d106cd6eccd8b

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: ca7dbd1078291f30df3fe4805de872df072db0e5
Pull Request: 0aa285656ec5a9e4960407656abc755fa146f020
Server: c789e6bb6f48e280805fe0f959f82559ca79a961

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: dacdc2ee84d84719e0e8badfaa6c6752d5f8ec7d
Pull Request: 0aa285656ec5a9e4960407656abc755fa146f020
Server: 35b901f541c3c909a94b8338c5c423bd7c038ece

**Comment by White-Sans** [comment]
#### Test Merge Removed

**Pull request merged**
