### PR TITLE
Weebstick

### PR DESCRIPTION
**Pull request by AsciiSquid**
## About The Pull Request
Adds the *Nanoforged Katana*, a blood-red blade that lets syndicate agents pretend they're ninjas, at least a little bit.
### Stats
Costs 10TC in the uplink.
Comes with a blade and sheath that can be equipped to the belt slot.
Blade is sharp (duh) and deals **25 Brute** with **50% armor piercing**.
Blade provides **40% melee block** chance and **20% projectile block** chance.
Using the sheath with the blade stored *primes* for a dash attack.
Clicking on any visible tile while *primed* will dash the user to the tile, dealing **15 Brute** to any mobs in-between and attacking for **25 Brute** at the target point.
Dash attacks are blocked by walls and other dense objects.
Alt-Clicking on the sheath with an open hand will speed-draw the weapon, making a flashy sound.

## Why It's Good For The Game

*[Art by Decompressed: Nuke Ops](https://mspfa.com/?s=39295&p=1)*

## Changelog
:cl:
add: Added weeaboo stick for 10TC
/:cl:

### CODE REVIEW

**Comment by zamolxius** [comment]
nice katana zero reference

**Comment by Shadowtail117** [comment]
Nice knife.

**Review by SynnGraffkin — APPROVED** [review]
image

**Pull request merged**
