### PR TITLE
Donot

### PR DESCRIPTION
**Pull request by Superyodeler**
## About The Pull Request

E:b:ent

## Why It's Good For The Game
E:b:ent

## Changelog
:cl: Superyodeler, triplezeta
add: New event
/:cl:

### CODE REVIEW

**Comment by Shadowtail117** [comment]
E🅱️ent

**Review by Shadowtail117 — CHANGES_REQUESTED** [review]
Map compiling errors:
image

**Comment by SynnGraffkin** [comment]
lilidoesntlikethis

**Comment by Maldaris** [comment]
https://user-images.githubusercontent.com/1953773/111457540-b14ec500-86ee-11eb-8fcf-88fa9fcd6f48.mov

**Pull request closed without merging**
