### PR TITLE
Plasmeme command helmets buff

### PR DESCRIPTION
**Pull request by LastCrusader105**
## About The Pull Request

Adds the buffs of the hardsuit HELMETS to plasmeme versions e.g CAPs helmet is now tempproof acid proof and provides a small brute buff etc

## Why It's Good For The Game

why should a plasmeme head of staff be held back by his helmet, yes they now have a slight buff when they arnt wearing the hardsuit but thats only to the head, i personally feel its not a big issue, plasmemes weak and sow as is

image of plasmemes wearing helmets and not burning (note the R&D has the research scanner attached to his helmet like the hardsuit version)
image

each head and atmos tech wearing helmet and their normal outfit and a copy wearing hardsuit
image

the aftermath
image

humans in hos and cmo suits
image

again please forgive fact images arnt of your server

## Changelog
:cl:
balance: added hardsuit helmet buffs to Plasmeme head of staffs helmets
fix: fixed atmos plasmeme helmet not being heat proof
add: rd plasmeme helmet has a bomb scanner
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
ok based

**Comment by LastCrusader105** [comment]
always bothered me that to be CE you had to sacrifice your plasmemeness
all ive done is copied and pasted the ce hardsuits stats which if you had hard suit helmet on would provide same
but then means you have the stats weather you have hardsuit or not, but id imagine the CE would have a fancy hat anyway

**Comment by LastCrusader105** [comment]
hold on a second lads, im also doing Atmos and adding hardsuit protection for caps,hos,rd protection

**Comment by LastCrusader105** [comment]
image

**Comment by LastCrusader105** [comment]
@MarkSuckerberg hello mark just a ping cause its gone stale, it is ready and tested

**Comment by TheNeoGamer42** [comment]
bro marks retired go harass maintainers not him

**Comment by untrius** [comment]
Ok, I took a look at this.

I noticed that you only changed the armor values for the command helmets.   I'm assuming this is intentional, but wanted to mention it just in case.  Like the engie hardsuit helmet has higher armor values than the engie plasmeme helmet.  This same idea would extend to the fact that you didn't give say a plasmeme doctor's helmet the armor values of a medical hardsuit helmet.

There were also a couple things I noticed that probably weren't intentional.  The HoS plasmeme helmet has a higher rad armor value (100) than the equivalent HoS hardsuit helmet (50).  Also, you didn't add the functions to the RD helmet to give it it's diagnostic HUD and it's explosion sense.  To add that, you'll probably want to copy the functions initialize, equipped, dropped, and sense_explosion from /obj/item/clothing/head/helmet/space/hardsuit/rd.

You're also missing modularization comments.  For files who's names don't start with "whitesands/" you'll need to add comments like "// WS Edit - plasmeme command helmets buff" on lines you change.  For multiline blocks, you can wrap them in something like this:
```
// WS Begin - plasmeme command helmets buff
my code changes
...
// WS End
```
All in all, it looks good.  Add the modularization comments and fix the HoS rad value, and I'll consider it ready.  I consider the non-command armor values and RD helmet functions optional.

**Comment by LastCrusader105** [comment]
> optional.

Yes the head helmets was intentional, as was the Atmos helmet to make it fireproof (to match the Atmos Hardsuit)

I also meant to change the regular sec plasmeme helmet to match the standard helmet sec has
Seems I forgot to add it, maybe I got the 2 sec ones confused
As for the rads, plasmemes are rad immune so just did it to 100, I shall change it to 50
I ping you when it’s done

**Comment by LastCrusader105** [comment]
@untrius it is good to go
the RD scanner was a pain but its done 😘

**Review by untrius — APPROVED** [review]
I tested this and it looks good.  Nice work on the RD helmet!

For transparency I'll mention that the sec helmet uses the armor values from the sec beret mixed with the sec plasmeme helmet's prior 100 for bio and fire.  I'm fine with this since sec would wear the beret considerably more often than the hardsuit helmet.

**Comment by Sparrowbird611** [comment]
Security plasmeme helmet is a great idea. I disagree with everything else however, and see no reason to give command  plasmemes body armor.

**Comment by Sparrowbird611** [comment]
On a related note, you gave the HoS helmet 25% bullet protection, and the default sec one 30% bullet protection. I assume this is a mistake. If not, I would give his helmet 30-35%, since he's meant to be a tad more armored than a grunt.

**Comment by LastCrusader105** [comment]
> Security plasmeme helmet is a great idea. I disagree with everything else however, and see no reason to give command plasmemes body armor. If any of these guys want to wear some degree of armor, they can get a hardsuit, since the hardsuit + hardsuit helmet works as a full suit last I checked. This rings especially true for the captain, who has a tank hardsuit. There is no need to give his helmet 50% resistance to several forms of damage.

the whole point of this PR is as a plasmeme i like to keep the look of a plasmeme so id like suit+plasma helmet, your right the suit still functions, but atheisticly it doesn't  

as for the HOS hardsuit, thats the HOS hardsuits helmet stats uneditted
image

**Comment by LastCrusader105** [comment]
> I tested this and it looks good. Nice work on the RD helmet!
> 
> For transparency I'll mention that the sec helmet uses the armor values from the sec beret mixed with the sec plasmeme helmet's prior 100 for bio and fire. I'm fine with this since sec would wear the beret considerably more often than the hardsuit helmet.

thank you, it took me a while cause you do it a different way to Beecode

as for the beret part it uses the standard sec helmet stats 
image

**Comment by Sparrowbird611** [comment]
I was mistaken on the HoS suit, as I assumed you were going off of HoS beret/helmet stats, rather than his hardsuit.

I really don't see why you need to keep the aesthetic, since you can deploy the hardsuit when there is a threat, then put your helmet back on when you don't need the armor. This feels like it fixes a non-existent issue. If  you want to make "armored plasmeme suits" purchasable from cargo, I'd support that more. Either way though I support your security helmet changes.

**Comment by untrius** [comment]
Ah, funny to know that the sec helmet and beret have the same armor values.

I did overlook the fact the HoS helmet armor values are lower.  They should probably be either:
1. Both the same as /obj/item/clothing/head/helmet
or
2. /obj/item/clothing/head/helmet/space/plasmaman/security/hos should match /obj/item/clothing/head/helmet/space/hardsuit/security/hos
and
/obj/item/clothing/head/helmet/space/plasmaman/security should match /obj/item/clothing/head/helmet/space/hardsuit/security

**Comment by LastCrusader105** [comment]
> I was mistaken on the HoS suit, as I assumed you were going off of HoS beret/helmet stats, rather than his hardsuit.
> 

no worries on the HOS, all the stats are just the hardsuit helmets applied to the plasmeme hats

> I really don't see why you need to keep the aesthetic, since you can deploy the hardsuit when there is a threat, then put your helmet back on when you don't need the armor. This feels like it fixes a non-existent issue. If you want to make "armored plasmeme suits" purchasable from cargo, I'd support that more. Either way though I support your security helmet changes.

because plasmeme helmets are cool, and when you swap you set on fire, plus granted its not a big issue on whitesands yet but when you get a noob doctor and he takes your hardsuit helmet off to do medical and you burn to death cause "why is he burning?" least with the hat they will just take your suit off and your hat

**Review by untrius — APPROVED** [review]

**Comment by Shadowtail117** [comment]
update the changelog with the bomb scanner feature, otherwise looks gucci

**Pull request merged**
