### PR TITLE
Poker Night at White Sands

### PR DESCRIPTION
**Pull request by Maldaris**
## About The Pull Request

Event content!

## Why It's Good For The Game

Gambling is debatably good. New content is absolutely good.

## Changelog
:cl:
add: Casino away mission
add: Tournament grade cards
add: Casino Chips, and Chip Vendor
/:cl:

### CODE REVIEW

**Comment by Maldaris** [comment]
Improvements needed before this gets fullmerged:

A tray sprite for chips that functions like the money bag. Because they're coins we already have the infrastructure to scoop these up ezpz.

Door permissions are just non-existent. Need to fix this to be some admeme-only role for most things, and on something we can hand out on a ID to casino staff.

APCs would be smart to have, even if the area is powered. Probably a SMES/power generator too.

**Comment by Maldaris** [comment]
alternatively yeet the speed-code coins and just make this whole thing run off holochips.

I don't really know why I didn't do that in the first place but chips seemed fun. Turns out they're just tedious.

**Comment by SynnGraffkin** [comment]
> Door permissions are just non-existent. Need to fix this to be some admeme-only role for most things, and on something we can hand out on a ID to casino staff.

Could set the doors to the centcom IDs, which are admin only to obtain.

**Comment by Maldaris** [comment]
> > Door permissions are just non-existent. Need to fix this to be some admeme-only role for most things, and on something we can hand out on a ID to casino staff.
> 
> Could set the doors to the centcom IDs, which are admin only to obtain.

So in my moth-tier sprint to get this done, you'll notice I put down centcom doors. That was to solve this problem. They do not come preconfigured.

**Comment by SynnGraffkin** [comment]
Nope, most doors aren't preconfigured. Easiest way to do it is find a door on another map, like centcom, and just copy the door.

**Comment by scarwolff** [comment]
metachips for metacoins

**Comment by Jack7D1** [comment]
F

**Pull request closed without merging**
