### PR TITLE
a bunch of titles and outfits

### PR DESCRIPTION
**Pull request by Maldaris**
## About The Pull Request

Adds more alternative titles for roles on the station.

## Why It's Good For The Game

Kinda funny how a simple job title can add a lot of variety to a round. Aims to give some flavorful outlets for a few jobs in the game that are lacking multiple alt titles/a senior title.

* Curator
  * Librarian
  * Historian
  * Archaeologist
  * Dungeon Master (Senior)
* Paramedic
  * Combat Life Saver
  * Field Surgeon (Senior)
* Cargo Tech
  * Cargonian (Senior)
* Quartermaster
  * Requisitions Officer
  * Chief Economist (Senior)
* Brig Phys.
  * Correctional Surgeon (Senior)
* Prisoner
  * Indentured Servant
  * Shotcaller (Senior)
* Shaft Miner
  * Righand
* Virologist
  * Microbiologist
  * Biological Weapons Specialist (Senior)
* Warden
  * Chief Master Sergeant (Senior)
* Mime
  * Living Statue (Senior)
* Chaplain
  * Monk
  * Imam
  * Rabbi
  * Atheist (Senior)
* CE
  * Maintenance Supervisor

TODO: 
- [x] Outfits for Chaplain variants
- [x] Junior Titles for most roles

## Changelog
:cl:
add: NT's HR department added more job titles
fix: Mislabled Cargonian hat
/:cl:

### CODE REVIEW

**Comment by scarwolff** [comment]
make the cargo senior title Cargonian ... GODDAMN!

**Comment by triplezeta** [comment]
ECONONY.................

**Comment by fakehayter** [comment]
execution supervisor.

**Comment by Maldaris** [comment]
Ready for review. @Superyodeler @untrius

**Review by Superyodeler — APPROVED** [review]

**Pull request merged**
