### PR TITLE
Adds enginseer robes to replace the old techpriest ones.

### PR DESCRIPTION
**Pull request by DerFlammenwerfer**
## About The Pull Request
Adds Enginseer robes to replace the techpriest robes in the robodrobe. I also added a concept sprite for the Omnissian Power Axe. Might need refinement/tweaking to look better, though.

## Why It's Good For The Game
The original robes look like hot garbo.

## Changelog
:cl:
add: Added Enginseer robes and the hood it comes with. The robe can hold guns, full size internals tanks, books, melee weapons, and null rods in its exosuit storage slot.
tweak: edited the robodrobe to have the new robes instead of the old ones.
imageadd: added the icons for the aforementioned robes
imageadd: also made what amounts to a placeholder sprite for an omnissian axe.
/:cl:

### CODE REVIEW

**Comment by AsciiSquid** [comment]
01010100011011110110000101110011011101000110010101110010001000000100110101101011001011100100100101001001001000000110000101110000011100000111001001101111011101100110010101110011

**Comment by theboy6545** [comment]
> 01010100011011110110000101110011011101000110010101110010001000000100110101101011001011100100100101001001001000000110000101110000011100000111001001101111011101100110010101110011

Translation: Toaster Mk.II approves

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by DerFlammenwerfer** [comment]
Pike off, abominable intelligence.

**Comment by SynnGraffkin** [comment]
@DerFlammenwerfer Got them conflicting files.

**Review by triplezeta — APPROVED** [review]
i will put my "this is an improvement" sticker on this PR, though I would love just *slightly* more contrast on the red

**Comment by SynnGraffkin** [comment]
Still has conflicting files.

**Pull request closed without merging**
