### PR TITLE
Add +ROD

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About The Pull Request

Adds a +ROD admin permission. Does nothing other than give you access to the "ROD" verb, which functions identically to smiting someone with the immovable rod. Available both in the Fun tab and when right-clicking a mob.

## Why It's Good For The Game

goddamnit dee

## Changelog
:cl:
admin: Added +ROD.
/:cl:

### CODE REVIEW

**Comment by Shadowtail117** [comment]
No idea why it considered changes..._within a fresh commit..._to be merge conflicts. That's kinda the whole point of version control, Github. :mothdonk:

**Comment by lunaboards-dev** [comment]
speedmerge time

**Comment by Shadowtail117** [comment]
turns out trying to make a change on a branch that's over 3 months old has some **_issues_**

**Comment by BrawlerHorde** [comment]
Can't testmerge this PR for some reason
agony

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: abfa3735de453c4b57d660b6395b8dd093357c00

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: e8c6725e5975e248cc015d29b3bf53b02312ce87
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: 8aaf1d92960aed79a6613351246470472346413c

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: e29ee0a0e1b68cab4f437b8af05286a0b7209311

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: 0c46f0c046c353b003e0df0f8b5d106cd6eccd8b

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: ca7dbd1078291f30df3fe4805de872df072db0e5
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: c789e6bb6f48e280805fe0f959f82559ca79a961

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: dacdc2ee84d84719e0e8badfaa6c6752d5f8ec7d
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: 35b901f541c3c909a94b8338c5c423bd7c038ece

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: f5a8346aa55c5189179a681ae74114fe54382bba
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: f9cf10d540a86e94bbf65b05344ba407ccc97d0d

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: c8b752239aef9ffc4e68d7bc7bbef816f462533c
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: d46bea6a85d7a8fca138151a32be363fa4ff9eb9

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: d0b00f8425ceac646b6ce473bc1494c9ebd37b02
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: 0899231c74c388b98b965aac407f7ad233a1aa1f

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: eb861ce0b96e035393d6ce959b95704858b23f53
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: 07a57557a3177bf81d4578a7d2929764d5ce6483

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8a9cbd8b817f506cb23cd836ac59a72af74f1787
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: 7b932bce04fb2a7fda877ae1df3f3d876eeea5ee

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8a9cbd8b817f506cb23cd836ac59a72af74f1787
Pull Request: 39df6c666d8c74a810b9fa2207de6c4e31e264ed
Server: dbac6e9bf5ed9d7defe9e0da1eadb359cd9ac642

**Review by untrius — APPROVED** [review]

**Comment by White-Sans** [comment]
#### Test Merge Removed

**Pull request merged**
