### PR TITLE
TG Merge 7a

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Ports a bunch of new tooling and a few new TGUI features/interfaces from TG.

## Why It's Good For The Game
We gotta roll with the changes

## Changelog
:cl: stylemistake, SpaceManiac, Mothblocks, tralezab, Seris02, spookydonut, Cyberboss, LemonInTheDark, Timberpoes, Watermelon914
add: TGUI secrets panel for admins.
add: TGUI list input.
add: .dmm merge driver for helping to resolve minor map conflicts.
add: CBT, something that many of our coders have been wanting for the longest time.
fix: TGchat lightmode tooltips work properly again.
fix: You can actually pay off pirates again.
tweak: The "who" verb's output is now in table form.
code: The mapmerge and other git hooks now support github desktop.
server: Be sure to update TGS's event scripts to support CBT.
/:cl:

### CODE REVIEW

**Comment by ADepressedPyroshark** [comment]
Where is the "I made a label for this" label, MARG???

**Comment by Shadowtail117** [comment]
all the labels

**Comment by dee-dubya** [comment]
>add: CBT, something that many of our coders have been wanting for the longest time.

should I ask you to elaborate or just leave that as is

**Comment by MarkSuckerberg** [comment]
no context needed

**Comment by Superyodeler** [comment]
I know I've been looking forwards to it.

**Pull request merged**
