### PR TITLE
Felinids  are now allergic to chocolate

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About The Pull Request

Felinids are now allergic to chocolate and will take toxin damage from it.

## Why It's Good For The Game

bad cat bad

## Changelog
:cl:
add: Felinids are now allergic to chocolate.
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
so when are we making flashes stun and blind moths again then

**Comment by untrius** [comment]
Not sure if intentional, but the cocoa powder doesn't metabolize.  So one bite can kill a felinid, if it's not removed from their system with say charcoal.

**Comment by lunaboards-dev** [comment]
oh, then i need to untestmerge it

**Comment by TheRealScarHomie** [comment]
> Not sure if intentional, but the cocoa powder doesn't metabolize. So one bite can kill a felinid, if it's not removed from their system with say charcoal.

feature

**Comment by Shadowtail117** [comment]
> Not sure if intentional, but the cocoa powder doesn't metabolize. So one bite can kill a felinid, if it's not removed from their system with say charcoal.

I feared not calling the parent would mess _something_ up. It COULD be a feature...something that requires emergency intervention otherwise it's invariably fatal...but that might be too harsh.

**Comment by untrius** [comment]
The way it is, it takes 1m40s to crit and 3m20s to kill, independent of dosage.

I'm not necessarily opposed to the idea, but it seems odd to me for a reagent to conditionally not be metabolized.  Is there another way we could implement it, like an anaphylaxis status_effect/debuff?

**Comment by Shadowtail117** [comment]
fixed

**Review by untrius — APPROVED** [review]

**Pull request merged**
