### PR TITLE
Lawnmower mows lawns (er... vines)

### PR DESCRIPTION
**Pull request by AsciiSquid**
## About The Pull Request
mower
The lawnmower now deletes any spacevine, glowshrooms, and alien weeds it comes across.
Additionally, the lawnmower actually needs to be driven to mow, opposed to before where you could just push it into things.

Now includes a non-emagged mower in the service tab of cargo for 10,000 credits and restricted to botany.

## Why It's Good For The Game
Things should be able to do the thing they are named after for doing.

## Changelog
:cl:
add: Lawnmowers now mow lawns
tweak: Lawnmowers mow lawns when lawnmower loans a lawn owner for operation.
/:cl:

### CODE REVIEW

**Comment by MrFagetti** [comment]
Siiiiiiiiiiiiip

**Comment by MrFagetti** [comment]
Siiiiiiiiiiiiip

**Comment by SynnGraffkin** [comment]
How many lawns can a lawnmower mow, if a lawnmower could mow lawns?

**Comment by fakehayter** [comment]
https://www.youtube.com/watch?v=NXookeCEbG8

**Comment by MrFagetti** [comment]
Abit crazy, but would it be bad if I ported the lawnmower and this functionality over to Lumos? I'll give credit to White Sands/Boomer Station.

**Comment by Maldaris** [comment]
> Abit crazy, but would it be bad if I ported the lawnmower and this functionality over to Lumos? I'll give credit to White Sands/Boomer Station.

You can port anything you want if you provide attribution 👍🏻

**Comment by MrFagetti** [comment]
Alright thanks yous. I really like this and think it'd be fun to have as a meme-y kinda dealio.

**Review by SynnGraffkin — APPROVED** [review]

**Pull request merged**
