### PR TITLE
Adds new moth based sprites!

### PR DESCRIPTION
**Pull request by Jack7D1**
## About The Pull Request
Sprites are courtesy of Papaporo Paprito over on Fulpstation!
https://twitter.com/papaporopaprito Here's his twitter, check it out!
This PR adds a bunch of different moth related sprites, including flight potion wings, new wing and fluff variants and even a new ai core screen!
Ports: https://github.com/TheSwain/Fulpstation/pull/415 and https://github.com/tgstation/tgstation/pull/56412
NOTE: The flight potions portion of this is largely a direct TG port, hence the lack of modularization.
A new system is implemented to make the multiple flight potion options possible, using radial menus.
image
mothlampech
image

## Why It's Good For The Game
The newly implemented radials selector makes adding secondary flight potion sprites very trivial in the future.
moffs worldwides

## Changelog
:cl:
add: A bunch of new moth sprites! Including a new Ai core screen, a couple wing variants and a new flight potion option! All sprites courtesy of Papaporo Paprito
/:cl:

### CODE REVIEW

**Review by triplezeta — APPROVED** [review]
Good sprites.

Yes. Very good.

There is no moth hivemind.

**Comment by Jack7D1** [comment]
Nooooooo! You cant just approve a draft!
It's not finished yet!

**Comment by triplezeta** [comment]
haha button go brr

**Comment by Jack7D1** [comment]
let the games begin

**Comment by Jack7D1** [comment]
I forgot two of the wing sprites, gonna do that sometime

**Comment by Jack7D1** [comment]
lets do this!

**Review by MarkSuckerberg — APPROVED** [review]
m

**Comment by Jack7D1** [comment]
mmmm

**Pull request merged**
