### PR TITLE
adds showers and stasis

### PR DESCRIPTION
**Pull request by LastCrusader105**
## About The Pull Request
Adds Showers to shuttles and stasis

## Why It's Good For The Game
makes shuttles up to boomer standards
and ends the stigmatism towards Plasmemes
whiteships now have showers in the engine room

## Changelog
:cl:
add: Added Showers And Stasis beds in the medical part of shuttles
/:cl:

### CODE REVIEW

**Comment by LastCrusader105** [comment]
i had a look at the error code and ive no idea what it even means, so I await a genius to look at it for me

**Comment by Shadowtail117** [comment]
It's just mapdiffbot having a stroke as always.

I recommend making your changelog a bit more descriptive than simply "adds showers and stasis beds". Where were they added?

**Comment by LastCrusader105** [comment]
> It's just mapdiffbot having a stroke as always.
> 
> I recommend making your changelog a bit more descriptive than simply "adds showers and stasis beds". Where were they added?

On the shuttle 😬
I joke, in the medical bit

**Comment by LastCrusader105** [comment]
Magically cleared itself

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
