### PR TITLE
Gruboid and Baby Gruboid monster

### PR DESCRIPTION
**Pull request by JohnTheAutist**
## About The Pull Request

Adds Gruboid and Baby Gruboid sprite and code. Whitesand equivalent for Goliath. Does not add it to whitesands planet yet. Pretty much just copied the Goliath script and replaced it with Gruboids. The Gruboid mostly is burried beneath the sand, but when it sees an enemy it pokes its head out. It will bite the player or dip its head below the sand again to shoot tentacles out of it's mouth. The baby Gruboids are tentacles that have split off on their own.

Gruboid

## Why It's Good For The Game

Gives Whitesands a distinct and more appropriate mob that replaces the Goliath.

## Changelog
:cl:
add: Gruboid
add: Baby Gruboid
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
You should isolate the new stuff from the old in this file. No point in having all the lavaland mobs like legion, basilisks, ect in this file that are duplicates.

**Review by SynnGraffkin — CHANGES_REQUESTED** [review]
Debete old, keep new

**Comment by JohnTheAutist** [comment]
If you mean remove the lavaland monsters from monster.dmi I did it.

**Comment by JohnTheAutist** [comment]
Gunna do another PR when I finish the other 2 sprites

**Pull request closed without merging**
