### PR TITLE
No More Chemspam: Redux

### PR DESCRIPTION
**Pull request by TheObserver-sys**
## About The Pull Request
This PR aims to change how plants handle nutrients and mutations. This directly ports the relevant portions of TGBotany, without bringing the other systems into play. This is adapted from the work I did to get this working on Citadel, with a few changes removed, and a few things tweaked.

What's new?:
Mutations are no longer handled by pouring an ocean of mutagen on a plant and hoping for the best. It's now done automatically through Instability, of which you can manipulate using fertilizers. This gene has 5 thresholds, dictating just how drastically the plant changes:
At 20+ Instability: Plants will weak roll their stats every life cycle, this is akin to 1 unit application of mutagen from the old hydroponics system.
At 30+ Instability: Plants, on harvest, have a chance of producing mutated offspring. This persists through every instability level.
At 40+ Instability: Plants will strong roll their stats every life cycle, akin to 2u+ applications of mutagen.
At 60+ Instability: Plants will attempt to roll new species every life cycle. Akin to a 5+ application of mutagen.
At 80+ Instability: Plants will constantly attempt to roll for new chemical and physical traits, the success of which increases as you get more and more unstable, upto 100.

Autogrow functionality: Control-Clicking a tray will activate a somewhat power intensive autogrow mode, which will kill weeds, keep the tray watered, and kill pests, while cutting the reagent drain in your tray in half. Good for when you need to step away, and you don't have earthsblood to stabilize the tray for a while.

A reason to upgrade the hydroponics trays: Autogrow is pretty decent on its own, but, upgrading the hydroponics trays quadruples the water containment, raises the reagent capacity to 50, and most importantly, cuts the reagent drain dramatically, meaning less time fiddling with plant chems.

Reworked and New Fertilizers:
Old fertilizers have been reformulated to be useful, and new fertilizers have come into being to interact with stats that you'd normally not be able to interact with outside the gene editor.
L4Z: Now lightly heals the plant, and increases plant instability, making it viable for actual use in obtaining new plants.

EZNutriment: Lightly adjusts instability, increases potency passively. Trays start with 10 units of this. A better bog standard.

Robust Harvest: Boosts yield and potency, drops instability. No longer applies the 30% bonus yield effect.

Liquid Earthquake: Buffs plant production speed, but also welcomes additional weed growth into the party. Use sparingly.

Endro Grow: Reduces the yield and potency of your plant, but makes it far more resilient, increasing the endurance stat directly.

Earthsblood: While earthsblood cannot be used to force permanent self sustain anymore, it is still very well worth obtaining. When applied to a tray, the plant inside will become immaculately healthy, plentiful, and potent, at the cost of absolute stability, making it nearly impossible to mutate a plant while it's still in the reagent tank.

Unstable Mutagen: Greatly boosts instability, but the tray gets poisoned for it. It's best to not use straight unstable mutagen, and instead mix it with Left 4 Zed and Ash to keep your plant healthy.

A new mode for the plant analyzer: Activating the Plant Analyzer in hand now allows you to switch between plant stats mode, and plant chems mode, which is useful to learning what new chemicals your plant has generated after a period of high instability. This can also be used on seeds and plants on the ground.

It also adds the Revolution and Mutation Lock functions to the plant gun, and enables plumbing by default. This is beyond modularity, and really is closer to being inline with TG code as is, while being just divergent enough.

Revolution Mode: Fire this at a tray, instantly mutate a plant. Costs a heavy amount of the plant gun's energy cell per shot.
Screenshot_2094

Mutation Lock: In melee range, press the gun against the hydroponics tray to bring up a menu showing a list of possible mutations.
image

## Why It's Good For The Game
Overall, this will significantly improve the QoL of hydroponics as a whole. It turns **all** of the basic tools into viable ones, allowing new botanists to pick up and play, and allowing more seasoned botanists the chance to experiment more often with expanded chemicals. 

## Some Valid Concerns:
Admittedly, with changes this strong, there will definitely some concerns that should be addressed.
"Doesn't this devalue strange seeds?"
Yes and no. It would be very easy to say that the 80 instability threshold  invalidates the purpose of strange seeds entirely, but I would be more than willing to argue that it improves strange seeds as well. This allows you, with some effort, to turn a completely useless package of strange seeds into something better over time, just by applying Left 4 Zed and a watchful eye.

"I'm going to be glued to botany for the entire round, aren't I?"
Not quite, provided that science actually functions, and grants you upgrades. Bare minimum, science should spare you some manipulators, which vastly improves the drain on your trays, and makes it even better when you toggle on autogrow. You won't be able to just set and forget, mind, but honestly, once the fridge and your bag has over 100 of a plant, you've more than done your job at that point.

"RNG??"
Admittedly, yes, this adds more RNG to botany, however, most of this RNG is designed to be more in your favor, excluding the instability 80 threshold. Being able to take a chance at 30+ instability to get mutated harvests, at least in my eyes, is an exceptional boon for speeding up towards a goal for the round. A decent example of this would be cannabis and tomatoes, both having 3+ potential mutations in one go. In addition, when the plant gun gets researched, you can manifest destiny, by either firing revolution mode directly at a tray to force mutations, or locking them in with the mutation lock function.

## Changelog
:cl: ArcaneMusic with tweaks from The0bserver
add: Adds and modifies fertilizers, as well as a new stat, Instability.
add: Upgrades plant guns to have two new functions. Revolution and Mutation Lock.
del: Removes the rather disused functionality of irrigation hoses.
tweak: Plant Analyzer have been upgraded. Using one in hand will now switch between a stat view of your plant, and a chemical view of your plant.
tweak: Trays now accept and store reagents, as well as coming with an autogrow mode. However, these upgrades came at the cost of old self sufficiency, meaning you must attend to your plants a bit more often.
tweak: Earthsblood, while not being able to gild trays anymore, has been found to still be quite powerful as a fertilizer.
/:cl:

### CODE REVIEW

**Comment by Baldir-Odensen** [comment]
More RNG to one of the most RNG heavy departments. Ties botanists to thier workstations preventing making it harder for them to aquire of station seeds. Makes it easier to aquire otherwise unavailable chemicals devaluing strange seeds and the chemicals in the normal plants

**Comment by SynnGraffkin** [comment]
Need Wiki update work before marge.

**Comment by Superyodeler** [comment]
Taking a look at this now

**Review by Superyodeler — CHANGES_REQUESTED** [review]
It works fine, but I think there should be a way to check which chemicals are inside the tray.

**Comment by TheObserver-sys** [comment]
Working on getting the wiki stuff done up. Stand by.

**Comment by TheObserver-sys** [comment]
Hydro page updated

**Comment by DerFlammenwerfer** [comment]
Currently (as of testmerge) the somatoray only has mutation, yield, and revolution modes. The Revolution projectile also fails to mutate plants, and Mutation Lock is entirely missing.

**Comment by White-Sans** [comment]
#### Test Merge Deployed

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 41d7189305b503ba153ebff4e8943a0222e9b10c
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: bb3f635ab0fb3cb83c1160218f2603841d27b0c2

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: 4abac5722228bcc662ce18e550d0f8d4ded2fbe8

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: fde570bb0d10fc6682540fbc5a299480af6e3ba8

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: abfa3735de453c4b57d660b6395b8dd093357c00

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: e8c6725e5975e248cc015d29b3bf53b02312ce87
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: 8aaf1d92960aed79a6613351246470472346413c

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: e29ee0a0e1b68cab4f437b8af05286a0b7209311

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: 0c46f0c046c353b003e0df0f8b5d106cd6eccd8b

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: ca7dbd1078291f30df3fe4805de872df072db0e5
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: c789e6bb6f48e280805fe0f959f82559ca79a961

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: dacdc2ee84d84719e0e8badfaa6c6752d5f8ec7d
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: 35b901f541c3c909a94b8338c5c423bd7c038ece

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: f5a8346aa55c5189179a681ae74114fe54382bba
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: f9cf10d540a86e94bbf65b05344ba407ccc97d0d

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: c8b752239aef9ffc4e68d7bc7bbef816f462533c
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: d46bea6a85d7a8fca138151a32be363fa4ff9eb9

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: d0b00f8425ceac646b6ce473bc1494c9ebd37b02
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: 0899231c74c388b98b965aac407f7ad233a1aa1f

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: eb861ce0b96e035393d6ce959b95704858b23f53
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: 07a57557a3177bf81d4578a7d2929764d5ce6483

**Comment by White-Sans** [comment]
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8a9cbd8b817f506cb23cd836ac59a72af74f1787
Pull Request: e0879bdacb52c311fc15531c4d5a746b1bc75b75
Server: 7b932bce04fb2a7fda877ae1df3f3d876eeea5ee

**Comment by untrius** [comment]
Closing because stale

**Comment by untrius** [comment]
Reopening because we're dumb and the bot got stuck.

**Comment by untrius** [comment]
Closing for real.  Feel free to reopen this in the future, if you decide to come back to it.

**Comment by White-Sans** [comment]
#### Test Merge Removed

**Pull request closed without merging**
