### PR TITLE
rebalances metacoins, adds tons of metacoin items

### PR DESCRIPTION
**Pull request by Maldaris**
## About The Pull Request

image

You're right, so I did it.

- Boosts greentext reward to 500 from 300
- Boosts medal reward to 300 from 100
- Boosts Escape Reward to 200 from 100
- Boosts Survive Reward to 100 from 50
- All of the above values scale down to half for short rounds (under 2 hours) and up to 150% (over 2 hours)

Also adds several new items to the metacoin shop.

## Why It's Good For The Game

Our average round time can be anywhere from 2 to 3 hours on a populated shift, and go on for literal days otherwise. We should alter metacoin rewards to reflect that.

## Changelog
:cl:
add: New Metacoin gear items
tweak: Boosted metacoin rewards
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Curious: How hard would it be to make the general survive or escape rate scale up the longer the round goes, up to a cap? Like, the base amount being where it is currently, and it scales up to a cap so people can't abuse random deadpop rounds for free coin.

**Comment by Maldaris** [comment]
> Curious: How hard would it be to make the general survive or escape rate scale up the longer the round goes, up to a cap? Like, the base amount being where it is currently, and it scales up to a cap so people can't abuse random deadpop rounds for free coin.

Not outside the realm of possibility, these are just scalar values. Lemme poke at the metacoin code and see how hard it would be to extract a meaningful timer out of it.

**Comment by SynnGraffkin** [comment]
Reading these commits though, lol.

**Review by Superyodeler — APPROVED** [review]

**Comment by Maldaris** [comment]
Passed vote 17 to 2, merging.

**Pull request merged**
