### PR TITLE
New map: ChimeraStation

### PR DESCRIPTION
**Pull request by lunaboards-dev**
## About The Pull Request

funny map where i shoved meta and packed together

## Why It's Good For The Game

it's not

## Changelog
:cl:
add: chimerastation
/:cl:

### CODE REVIEW

**Review by Superyodeler — APPROVED** [review]

**Comment by lunaboards-dev** [comment]
oh god

**Comment by Superyodeler** [comment]
You created this monster

**Comment by Moccha-Bee** [comment]
> You created this monster

but nobody wants monster no more they want slim shady...

**Comment by lunaboards-dev** [comment]
you know what

### merge my fucking pr

**Pull request closed without merging**
